-- Create role for Airflow
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE ROLE AIRFLOW_ROLE
    COMMENT = 'Role for Airflow to access Insurance DWH';

-- Grant warehouse usage
GRANT USAGE ON WAREHOUSE INSURANCE_WH TO ROLE AIRFLOW_ROLE;
GRANT OPERATE ON WAREHOUSE INSURANCE_WH TO ROLE AIRFLOW_ROLE;

-- Grant database and schema access
GRANT USAGE ON DATABASE INSURANCE_DWH TO ROLE AIRFLOW_ROLE;
GRANT USAGE ON ALL SCHEMAS IN DATABASE INSURANCE_DWH TO ROLE AIRFLOW_ROLE;


-- Create user for Airflow
CREATE OR REPLACE USER AIRFLOW_USER
    PASSWORD = 'Airflow@2024'
    DEFAULT_ROLE = AIRFLOW_ROLE
    DEFAULT_WAREHOUSE = INSURANCE_WH
    COMMENT = 'Service account for Airflow';

-- Grant role to user
GRANT ROLE AIRFLOW_ROLE TO USER AIRFLOW_USER;

-- Grant schema access
GRANT USAGE ON SCHEMA INSURANCE_DWH.BRONZE TO ROLE AIRFLOW_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_DWH.SILVER TO ROLE AIRFLOW_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_DWH.GOLD TO ROLE AIRFLOW_ROLE;

-- Grant table permissions on BRONZE (where Airflow loads data)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA INSURANCE_DWH.BRONZE TO ROLE AIRFLOW_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA INSURANCE_DWH.BRONZE TO ROLE AIRFLOW_ROLE;


-- Grant warehouse permissions
GRANT USAGE ON WAREHOUSE INSURANCE_WH TO ROLE AIRFLOW_ROLE;
GRANT OPERATE ON WAREHOUSE INSURANCE_WH TO ROLE AIRFLOW_ROLE;
GRANT MODIFY ON WAREHOUSE INSURANCE_WH TO ROLE AIRFLOW_ROLE;

-- Verify it worked
SHOW GRANTS TO ROLE AIRFLOW_ROLE;


-- Verify grants
SHOW GRANTS TO ROLE AIRFLOW_ROLE;




USE ROLE ACCOUNTADMIN;

-- Check if DBT_USER exists
SHOW USERS LIKE 'DBT_USER';

-- Check if DBT_ROLE exists
SHOW ROLES LIKE 'DBT_ROLE';

-- If they don't exist, run this:
CREATE OR REPLACE ROLE DBT_ROLE;
CREATE OR REPLACE USER DBT_USER PASSWORD = 'Dbt@2024' DEFAULT_ROLE = DBT_ROLE DEFAULT_WAREHOUSE = INSURANCE_WH;
GRANT ROLE DBT_ROLE TO USER DBT_USER;

-- Grant permissions
GRANT USAGE ON WAREHOUSE INSURANCE_WH TO ROLE DBT_ROLE;
GRANT USAGE ON DATABASE INSURANCE_DWH TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_DWH.BRONZE TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_DWH.SILVER TO ROLE DBT_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_DWH.GOLD TO ROLE DBT_ROLE;

GRANT SELECT ON ALL TABLES IN SCHEMA INSURANCE_DWH.BRONZE TO ROLE DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA INSURANCE_DWH.SILVER TO ROLE DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA INSURANCE_DWH.GOLD TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA INSURANCE_DWH.SILVER TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA INSURANCE_DWH.GOLD TO ROLE DBT_ROLE;



-- Grant database level permissions
GRANT CREATE SCHEMA ON DATABASE INSURANCE_DWH TO ROLE DBT_ROLE;
GRANT USAGE ON DATABASE INSURANCE_DWH TO ROLE DBT_ROLE;

-- Grant schema permissions
GRANT ALL ON SCHEMA INSURANCE_DWH.BRONZE TO ROLE DBT_ROLE;
GRANT ALL ON SCHEMA INSURANCE_DWH.SILVER TO ROLE DBT_ROLE;
GRANT ALL ON SCHEMA INSURANCE_DWH.GOLD TO ROLE DBT_ROLE;

-- Grant table permissions
GRANT SELECT ON ALL TABLES IN SCHEMA INSURANCE_DWH.BRONZE TO ROLE DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA INSURANCE_DWH.SILVER TO ROLE DBT_ROLE;
GRANT ALL ON ALL TABLES IN SCHEMA INSURANCE_DWH.GOLD TO ROLE DBT_ROLE;

-- Grant future permissions
GRANT SELECT ON FUTURE TABLES IN SCHEMA INSURANCE_DWH.BRONZE TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA INSURANCE_DWH.SILVER TO ROLE DBT_ROLE;
GRANT ALL ON FUTURE TABLES IN SCHEMA INSURANCE_DWH.GOLD TO ROLE DBT_ROLE;

SHOW TABLES IN SCHEMA BRONZE;

-------------------
GRANT USAGE ON DATABASE INSURANCE_DWH TO ROLE AIRFLOW_ROLE;
GRANT USAGE ON SCHEMA INSURANCE_DWH.BRONZE TO ROLE AIRFLOW_ROLE;
GRANT CREATE TABLE ON SCHEMA INSURANCE_DWH.BRONZE TO ROLE AIRFLOW_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA INSURANCE_DWH.BRONZE TO ROLE AIRFLOW_ROLE;
-- docker exec -it airflow-docker-airflow-scheduler-1 airflow dags trigger etl_postgres_to_snowflake


-------------------