name: 'insurance_dbt'

version: '1.0'

config-version: 2

profile: 'insurance_dbt'

model-paths: ["models"]

models:

  insurance_dbt:

    silver:
      +materialized: table
      +schema: SILVER

    gold:
      +materialized: table
      +schema: GOLD